### ISSUE TITLE
env check switches to development all the time

### ISSUE THREAD

**Issue by reshadf** [juanpablob/angular-environment#22]
Hi, Out of nowhere the environment switches to development on my production server. Is this a known bug?

**Comment by juanpablob** [comment]
I think you probably solved it while ago, but anyway I'll look into it. Thank you and sorry for the delay.

**Comment by juanpablob** [comment]
@reshadf I just found what's happening. Probably you're not matching the exact domain, i.e. `2nd.1st.com`, instead you're using `1st.com` to match any domain ending with `1st.com` and that's the bug I just fixed and I'm introducing an update tomorrow sunday ;)

**Comment by juanpablob** [comment]
The version has just released. Enjoy.

**Comment by juanpablob** [comment]
I just released a last version because I forgot to add the compiled scripts in the previous release. Sorry about that. Now you can update to latest.

**Comment by juampick** [comment]
Hi.. @juanpablob  I think we are currently having this issue on the latest 1.0.7 version. 
It's not matching correctly when using subdomains like: 
```
dev: 'dapp.test.com',
test: 'tapp.test.com',
production: 'app.test.com'.
```
It's always setting as the **production** to be the environment, incorrectly.

I think the issue is on the check() method, and this commit:
https://github.com/juanpablob/angular-environment/commit/3cd588eb6de979fb3f6dae5310e82f91979e2a8d

Could you please take a look?
