### ISSUE TITLE
Angular environment returning development

### ISSUE THREAD

**Issue by mcblum** [juanpablob/angular-environment#23]
So we have a very strange problem. We use this package on almost every angular app we have, and it's been flawless, except for on our most recent project. I have checked the code 1000 times and it's literally copied and pasted from the other projects so I'm 99% sure it works, but no matter what we do Angular Environment always returned development. 

I'm not sure how this can be because we have 10 or more implementations that worked without issue, but it seems to be the case.

Anything I can try to attempt to get it to work?

Edit: also should note I've tried manually calling `set('staging')` and even that doesn't work. Every time it goes to actually read the environment and the variables, it grabs the development ones.

**Comment by juanpablob** [comment]
Hello @mcblum! I've been kind of busy and I haven't the time for keep developing on this project but now I have the time, so I'll check the issue, because few people already told me about the same issue. I'll look into it and I'll let you know as soon as I upload some update within next days.

Cheers!

**Comment by mcblum** [comment]
That's wonderful @juanpablob, thank you so much. I wanted to try and help but I felt a little underqualified :) I know open source stuff can be a pain because it's like "hey you know that thing you did for free, well we need it NOW so HURRY UP." I appreciate your efforts!

**Comment by mcblum** [comment]
@juanpablob OH NO. I'm a moron. I forgot to run `.check()`. I decided I would try to contribute something and setting breakpoints and such led me to this.

I'm really sorry to have bothered you!

**Comment by juanpablob** [comment]
@mcblum hahaha, shit happens! Anyway, tomorrow sunday I will release a new version that fix a problem related to subdomains, because the only thing you can do today is match exact domains, not "wildcards". Let's say you have multiple instances of your app: `instance1.production.com`, `instance2.production.com` and so on… to avoid put all the domains inside production env variable, sounds logic to have just `production.com` as production domain, but the plugins fails if you do that. Tomorrow's release include a fix for that and also now you will be able to use `*` as wildcard for domains, i.e. `*.domain.com` or `subdomain.*.com`.

Cheers!

**Comment by mcblum** [comment]
That's awesome!  Thanks for being so quick on this @juanpablob!

**Comment by juanpablob** [comment]
The version has just released. Enjoy.

**Comment by juanpablob** [comment]
I just released a last version because I forgot to add the compiled scripts in the previous release. Sorry about that. Now you can update to latest.
