### ISSUE TITLE
Version 1.0.3 heroku & subdomains issue

### ISSUE THREAD

**Issue by victorhazbun** [juanpablob/angular-environment#5]
I have been using the version 1.0.2 like this: 

```
  domains: {
    development: ['localhost'],
    staging: ['herokuapp.com'],
    production: ['domain.com']
  }
```

And it worked.

Then when I upgraded to the version 1.0.3 and the staging domain was not recognised because it was returning the vars from development domain.

What I did to make did to make it work again was:

```
 domains: {
    development: ['localhost'],
    staging: ['staging-frontend-domain.herokuapp.com'],
    production: ['www.domain.com']
  }
```

The only difference is that now staging and production have the subdomain specified.

It will be a good idea to write some tests before releasing a new version... just saying...

**Comment by juanpablob** [comment]
@victorhazbun87 Thank you for your feedback. Actually, the last release makes some changes during domain comprobation to look the exact domain, not looking to match the domain within any url as worked in 1.0.2 (which was causing this issue: https://github.com/juanpablob/angular-environment/issues/3). That's why I'm working on a new release where you'll be able to add wildcards to domains, i.e: `*.herokuapp.com` or `subdomain.herokuapp.com` I'll let you know when it's finished.
